/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AeIcon5Component {
        /**
          * Identifier for render options
         */
        "adaept": string;
        /**
          * Size of the icon
         */
        "aesize": string;
        /**
          * Title for the panel - visible or hidden
         */
        "aetitle": string;
        /**
          * Type of the icon (WIP - identify round)
         */
        "aetype": string;
        /**
          * Accessible label for the icon, applied to the inner `<ion-icon>`'s `aria-label`. Falls back to `name` when not set (see `resolvedArialabel`) so consumers never have to pass it just to avoid an empty/undefined accessible name — set it explicitly to override.
         */
        "arialabel": string;
        /**
          * Color of the icon
         */
        "color": string;
        /**
          * When true, the rendered `<ion-icon>` is marked `aria-hidden` and gets no `aria-label` — for icons that are part of a larger decorative group whose *container* carries the meaningful label (e.g. several icons spelling out one word), so a screen reader doesn't announce each fragment separately.
          * @default false
         */
        "decorative": boolean;
        /**
          * Name of the icon
         */
        "name": string;
        /**
          * Icon source set (D3 seam). Only 'ionicons' is implemented this cycle; additional providers (e.g. 'iconify:*') can be added without API churn.
          * @default 'ionicons'
         */
        "set": string;
        /**
          * Url of the icon
         */
        "src": string;
        /**
          * Show/Hide the panel
         */
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLAeIcon5ComponentElement extends Components.AeIcon5Component, HTMLStencilElement {
    }
    var HTMLAeIcon5ComponentElement: {
        prototype: HTMLAeIcon5ComponentElement;
        new (): HTMLAeIcon5ComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ae-icon5-component": HTMLAeIcon5ComponentElement;
    }
}
declare namespace LocalJSX {
    interface AeIcon5Component {
        /**
          * Identifier for render options
         */
        "adaept"?: string;
        /**
          * Size of the icon
         */
        "aesize"?: string;
        /**
          * Title for the panel - visible or hidden
         */
        "aetitle"?: string;
        /**
          * Type of the icon (WIP - identify round)
         */
        "aetype"?: string;
        /**
          * Accessible label for the icon, applied to the inner `<ion-icon>`'s `aria-label`. Falls back to `name` when not set (see `resolvedArialabel`) so consumers never have to pass it just to avoid an empty/undefined accessible name — set it explicitly to override.
         */
        "arialabel"?: string;
        /**
          * Color of the icon
         */
        "color"?: string;
        /**
          * When true, the rendered `<ion-icon>` is marked `aria-hidden` and gets no `aria-label` — for icons that are part of a larger decorative group whose *container* carries the meaningful label (e.g. several icons spelling out one word), so a screen reader doesn't announce each fragment separately.
          * @default false
         */
        "decorative"?: boolean;
        /**
          * Name of the icon
         */
        "name"?: string;
        /**
          * Icon source set (D3 seam). Only 'ionicons' is implemented this cycle; additional providers (e.g. 'iconify:*') can be added without API churn.
          * @default 'ionicons'
         */
        "set"?: string;
        /**
          * Url of the icon
         */
        "src"?: string;
    }

    interface AeIcon5ComponentAttributes {
        "adaept": string;
        "set": string;
        "aesize": string;
        "aetype": string;
        "arialabel": string;
        "decorative": boolean;
        "color": string;
        "name": string;
        "src": string;
        "aetitle": string;
    }

    interface IntrinsicElements {
        "ae-icon5-component": Omit<AeIcon5Component, keyof AeIcon5ComponentAttributes> & { [K in keyof AeIcon5Component & keyof AeIcon5ComponentAttributes]?: AeIcon5Component[K] } & { [K in keyof AeIcon5Component & keyof AeIcon5ComponentAttributes as `attr:${K}`]?: AeIcon5ComponentAttributes[K] } & { [K in keyof AeIcon5Component & keyof AeIcon5ComponentAttributes as `prop:${K}`]?: AeIcon5Component[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ae-icon5-component": LocalJSX.IntrinsicElements["ae-icon5-component"] & JSXBase.HTMLAttributes<HTMLAeIcon5ComponentElement>;
        }
    }
}
