/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AeIcon5 {
        /**
          * Identifier for render options
         */
        "adaept": string;
        /**
          * Size of the icon
         */
        "aesize": string;
        /**
          * Title for the panel - visible or hidden
         */
        "aetitle": string;
        /**
          * Type of the icon (WIP - identify round)
         */
        "aetype": string;
        /**
          * Aaria label of the icon
         */
        "arialabel": string;
        /**
          * Color of the icon
         */
        "color": string;
        /**
          * Name of the icon
         */
        "name": string;
        /**
          * Url of the icon
         */
        "src": string;
        /**
          * Show/Hide the panel
         */
        "toggle": () => Promise<void>;
    }
}
declare global {
    interface HTMLAeIcon5Element extends Components.AeIcon5, HTMLStencilElement {
    }
    var HTMLAeIcon5Element: {
        prototype: HTMLAeIcon5Element;
        new (): HTMLAeIcon5Element;
    };
    interface HTMLElementTagNameMap {
        "ae-icon5": HTMLAeIcon5Element;
    }
}
declare namespace LocalJSX {
    interface AeIcon5 {
        /**
          * Identifier for render options
         */
        "adaept"?: string;
        /**
          * Size of the icon
         */
        "aesize"?: string;
        /**
          * Title for the panel - visible or hidden
         */
        "aetitle"?: string;
        /**
          * Type of the icon (WIP - identify round)
         */
        "aetype"?: string;
        /**
          * Aaria label of the icon
         */
        "arialabel"?: string;
        /**
          * Color of the icon
         */
        "color"?: string;
        /**
          * Name of the icon
         */
        "name"?: string;
        /**
          * Url of the icon
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "ae-icon5": AeIcon5;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ae-icon5": LocalJSX.AeIcon5 & JSXBase.HTMLAttributes<HTMLAeIcon5Element>;
        }
    }
}
